name: Apply Argo CD Application

workflow_run:
    workflows: ["Build and Deploy Go App"]  #third workflow
    types:
      - completed

jobs:
  apply-argocd-app:
    runs-on: ubuntu-latest
    needs: install-argocd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name aws_eks_cluster.main.name

      - name: Apply Argo CD Application
        run: |
          kubectl apply -f kubernetes/argocd/argocd-app.yaml
