name: Build and Deploy Go App

workflow_run:
    workflows: ["Install Argo CD on EKS"]  #second workflow
    types:
      - completed

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5

      - name: Build Go App
        run: go build -o go-web-app

      - name: Run Go Tests
        run: go test ./...

  docker-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: docker-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update image tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/go-web-app/Values.yaml

      - name: Commit and push chart changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add helm/go-web-app/Values.yaml
          git commit -m "Update image tag to ${{ github.run_id }}"
          git push