name: Install Argo CD on EKS

workflow_run:
    workflows: ["Provision AWS Infrastructure"]  #first workflow
    types:
      - completed

jobs:
  install-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name aws_eks_cluster.main.name

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.2

      - name: Create Argo CD namespace
        run: |
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

      - name: Add Argo CD Helm repo
        run: helm repo add argo https://argoproj.github.io/argo-helm

      - name: Update Helm repos
        run: helm repo update

      - name: Install Argo CD via Helm
        run: |
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --set server.service.type=LoadBalancer \
            --wait